// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication4.Data;

#nullable disable

namespace WebApplication4.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20221012120410_addingusertable")]
    partial class addingusertable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication4.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "HYD",
                            Email = "Student1@gmail.com",
                            Name = "Student 1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "HYD",
                            Email = "Student2@gmail.com",
                            Name = "Student 2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "HYD",
                            Email = "Student2@gmail.com",
                            Name = "Student 3"
                        },
                        new
                        {
                            Id = 4,
                            Address = "HYD",
                            Email = "Student3@gmail.com",
                            Name = "Student 4"
                        });
                });

            modelBuilder.Entity("WebApplication4.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fullname = "Student 1",
                            Password = "Password1",
                            Role = "Student",
                            Username = "Student1"
                        },
                        new
                        {
                            Id = 2,
                            Fullname = "Student 2",
                            Password = "Password2",
                            Role = "Student",
                            Username = "Student2"
                        },
                        new
                        {
                            Id = 3,
                            Fullname = "Student 3",
                            Password = "Password3",
                            Role = "Student",
                            Username = "Student3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
